# Generated by Django 4.2.2 on 2023-07-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minicucina', '0002_alter_plat_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='minicucina/images/desserts/')),
                ('jour', models.CharField(max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='minicucina/images/entrees/')),
                ('jour', models.CharField(max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
            ],
        ),
    ]
