# Generated by Django 4.2.2 on 2023-07-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minicucina', '0003_dessert_entree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entree',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
