# Generated by Django 4.2.2 on 2023-07-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minicucina', '0005_alter_dessert_id_alter_entree_id_alter_plat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='image',
            field=models.ImageField(upload_to='minicucina/static/minicucina/images/desserts/'),
        ),
    ]
