# Generated by Django 4.2.2 on 2023-07-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minicucina', '0006_alter_dessert_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert',
            name='nom_fichier',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='image',
            field=models.ImageField(upload_to='images/desserts/'),
        ),
        migrations.AlterField(
            model_name='entree',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entree',
            name='image',
            field=models.ImageField(upload_to='images/entrees/'),
        ),
        migrations.AlterField(
            model_name='plat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plat',
            name='image',
            field=models.ImageField(upload_to='images/plats/'),
        ),
    ]
