# Generated by Django 4.2.2 on 2023-07-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minicucina', '0008_entree_nom_fichier_plat_nom_fichier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dessert',
            options={'ordering': ['order', 'nom']},
        ),
        migrations.AlterModelOptions(
            name='entree',
            options={'ordering': ['order', 'nom']},
        ),
        migrations.AlterModelOptions(
            name='plat',
            options={'ordering': ['order', 'nom']},
        ),
        migrations.AddField(
            model_name='dessert',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entree',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plat',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
