# Generated by Django 4.2.2 on 2023-07-25 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minicucina', '0010_alter_dessert_options_alter_entree_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dessert',
            options={},
        ),
        migrations.AlterModelOptions(
            name='entree',
            options={},
        ),
        migrations.AlterModelOptions(
            name='plat',
            options={},
        ),
    ]
