# Generated by Django 4.2.2 on 2023-07-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minicucina', '0011_alter_dessert_options_alter_entree_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert',
            name='ordre',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='entree',
            name='ordre',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plat',
            name='ordre',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
