# Generated by Django 4.2.2 on 2023-07-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minicucina', '0012_dessert_ordre_entree_ordre_plat_ordre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dessert',
            options={'ordering': ['ordre']},
        ),
        migrations.AlterModelOptions(
            name='entree',
            options={'ordering': ['ordre']},
        ),
        migrations.AlterModelOptions(
            name='plat',
            options={'ordering': ['ordre']},
        ),
    ]
