# Generated by Django 4.2.2 on 2023-08-07 13:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('minicucina', '0013_alter_dessert_options_alter_entree_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dessert',
            options={},
        ),
        migrations.AlterModelOptions(
            name='entree',
            options={},
        ),
        migrations.AlterModelOptions(
            name='plat',
            options={},
        ),
        migrations.RemoveField(
            model_name='dessert',
            name='ordre',
        ),
        migrations.RemoveField(
            model_name='entree',
            name='ordre',
        ),
        migrations.RemoveField(
            model_name='plat',
            name='ordre',
        ),
        migrations.AlterField(
            model_name='dessert',
            name='jour',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi')], default=('lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi'), max_length=100),
        ),
        migrations.AlterField(
            model_name='entree',
            name='jour',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi')], default=('lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi'), max_length=100),
        ),
        migrations.AlterField(
            model_name='plat',
            name='jour',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi')], default=('lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi'), max_length=100),
        ),
    ]
