# Generated by Django 4.2.2 on 2023-08-08 16:50

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('minicucina', '0014_alter_dessert_options_alter_entree_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boisson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='minicucina/static/minicucina/images/boissons/')),
                ('nom_fichier', models.CharField(blank=True, editable=False, max_length=100)),
                ('jour', multiselectfield.db.fields.MultiSelectField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi')], default=('lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi'), max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
            ],
        ),
    ]
