# Generated by Django 4.2.2 on 2023-08-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minicucina', '0015_boisson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boisson',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='dessert',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='entree',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='plat',
            options={'ordering': ['id']},
        ),
    ]
